version: '3.9'

services:
  tasks-svc:
    image: 'tasks-svc:latest'
    build:
      context: './'
      dockerfile: 'services/tasks/tasks.Dockerfile'
    ports:
      - "8082:8082"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - LOGGER_LEVEL=release
      - DB_PASSWORD=${TASKS_POSTGRES_PASSWORD}
    networks:
      - new
    volumes:
      - migrations-data:/services/tasks/migrations

  postgres:
    restart: always
    image: 'postgres:latest'
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_DB=${TASKS_POSTGRES_NAME}
      - POSTGRES_HOST=${TASKS_POSTGRES_HOST}
      - POSTGRES_USER=${TASKS_POSTGRES_USER}
      - POSTGRES_PASSWORD=${TASKS_POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "su", "postgres", "-c", "pg_isready" ]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - new
    volumes:
      - pgdata:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate
    command: ["-path", "/migrations", "-database",  "postgres://${TASKS_POSTGRES_USER}:${TASKS_POSTGRES_PASSWORD}@${TASKS_POSTGRES_HOST}:${TASKS_POSTGRES_PORT}/${TASKS_POSTGRES_NAME}?sslmode=disable", "up", "3"]
    links:
      - postgres
    depends_on:
      - postgres
    networks:
      - new
    volumes:
      - migrations-data:/migrations

networks:
  new:

volumes:
  pgdata:
  migrations-data:
