apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: kube-system
  labels:
    k8s-app: fluent-bit
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        5
        Daemon       Off
        Log_Level    info
        Parsers_File parsers.conf
        HTTP_Server  On
        HTTP_Listen  0.0.0.0
        HTTP_Port    2020
        Mem_Buf_Limit 5MB  # Ограничиваем максимальный размер буфера в памяти

    [INPUT]
        Name             tail
        Path             /var/log/containers/*.log
        Parser           docker
        DB               /tail-db/tail-containers-state.db
        Mem_Buf_Limit    5MB
        Skip_Long_Lines  On
        Refresh_Interval 10

    [OUTPUT]
        Name  stdout
        Match *

  parsers.conf: |
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On
        Decode_Field_As json log
        Time_Key    log.time

    [PARSER]
        Name        docker_no_time
        Format      json
        Decode_Field_As json log
        Time_Keep   On
