apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasks-svc
  template:
    metadata:
      labels:
        app: tasks-svc
    spec:
      containers:
        - name: tasks-svc
#          image: services/tasks:latest  # образ должен быть доступен в репозитории
          image: sirdaukar/hse_wishlist:latest
          ports:
            - containerPort: 8082
          env:
            - name: CONFIG_TASKS
              value: ./services/tasks/config/config.local.yml
            - name: ENV_FILE
              value: ./services/tasks/.env
            - name: LOGGER_LEVEL
              value: debug
#            - name: DB_PASSWORD
#              value: password
#              valueFrom:
#                secretKeyRef:
#                  name: tasks-postgres-secret
#                  key: password
#            - name: POSTGRES_DB
#              value: tasks_db
#            - name: POSTGRES_USER
#              value: postgres
#            - name: POSTGRES_PASSWORD
#              value: password
#            - name: POSTGRES_HOST
#              value: tasks_db
#            - name: POSTGRES_PORT
#              value: "5432"
#            - name: POSTGRES_SSL
#              value: disable
          volumeMounts:
            - name: migrations-data
              mountPath: /services/tasks/migrations
#      depends_on:
#        - name: postgres
#          condition: service-healthy
      volumes:
        - name: migrations-data
          emptyDir: {}