apiVersion: v1
kind: ConfigMap
metadata:
  name: migrate-configmap
data:
  000001_init_accounts.up.sql: |
    CREATE TABLE accounts
    (
        uuid       UUID      NOT NULL DEFAULT gen_random_uuid(),
        login      VARCHAR   NOT NULL,
        password   VARCHAR   NOT NULL,
        created_at TIMESTAMP NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
        PRIMARY KEY (uuid)
    );
    
    CREATE
        OR REPLACE FUNCTION update_updated_at()
        RETURNS TRIGGER AS
    $$
    BEGIN
        NEW.updated_at = NOW();
        RETURN NEW;
    END;
    $$ language 'plpgsql';
    
    
    CREATE TRIGGER update_accounts_updated_at
        BEFORE UPDATE
        ON accounts
        FOR EACH ROW
    EXECUTE FUNCTION update_updated_at();

  000002_init_tasks.up.sql: |
    CREATE TABLE tasks
    (
        uuid       UUID      NOT NULL DEFAULT gen_random_uuid(),
        name       VARCHAR   NOT NULL,
        text       VARCHAR   NOT NULL,
        status     VARCHAR   NOT NULL,
        created_by UUID      NOT NULL,
        started_at TIMESTAMP NOT NULL,
        ended_at   TIMESTAMP NOT NULL,
        created_at TIMESTAMP NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
        PRIMARY KEY (uuid)
    );
    
    
    CREATE TRIGGER update_tasks_updated_at
        BEFORE UPDATE
        ON tasks
        FOR EACH ROW
    EXECUTE FUNCTION update_updated_at();
