apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-config
  namespace: monitoring
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:

    exporters:
      debug:
        verbosity: detailed
      otlp/jaeger:
        endpoint: jaeger:4317
        tls:
          insecure: true

    extensions:
      health_check:
      pprof:
        endpoint: :1888
      zpages:
        endpoint: :55679

    service:
      extensions: [ health_check, pprof, zpages ]
      pipelines:
        traces:
          receivers: [ otlp ]
          exporters: [ otlp/jaeger ]
