apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 30s
      scrape_timeout: 30s
      evaluation_interval: 30s

    alerting:
      alertmanagers:
        - static_configs:
            - targets: [ ]

    scrape_configs:
      - job_name: 'prometheus'
        honor_timestamps: true
        scrape_interval: 30s
        scrape_timeout: 30s
        metrics_path: /metrics
        scheme: http
        static_configs:
          - targets: [ 'localhost:9090' ]
      - job_name: 'taskManagerService'
        honor_timestamps: true
        scrape_interval: 30s
        scrape_timeout: 30s
        metrics_path: /system/metrics/prometheus
        scheme: http
        static_configs:
          - targets: [ 'tasks-svc:8082' ]
