openapi: 3.0.0
info:
  title: Task Service API
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/v1
paths:
  /tasks/{id}:
    get:
      tags:
        - Task
      summary: Get task by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskGet'
  /tasks:
    get:
      tags:
        - Task
      summary: List tasks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskFilter'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TaskGet'
    post:
      tags:
        - Task
      summary: Create a task
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskCreate'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModelUUID'
    put:
      tags:
        - Task
      summary: Update a task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskUpdate'
      responses:
        '200':
          description: Successful operation
  /tasks/{id}/end:
    patch:
      tags:
        - Task
      summary: End a task
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Successful operation
components:
  schemas:
    TaskGet:
      type: object
      properties:
        UUID:
          type: string
          format: uuid
        CreatedBy:
          type: string
          format: uuid
        Percent:
          type: number
        StartedAt:
          type: string
          format: date-time
        EndedAt:
          type: string
          format: date-time
        Status:
          type: string
        CreatedAt:
          type: string
          format: date-time
        LastUpdateAt:
          type: string
          format: date-time
      required:
        - UUID
        - CreatedBy
        - Percent
        - StartedAt
        - EndedAt
        - Status
        - CreatedAt
        - LastUpdateAt
    TaskCreate:
      type: object
      properties:
        CreatedBy:
          type: string
          format: uuid
        Percent:
          type: number
        StartedAt:
          type: string
          format: date-time
        EndedAt:
          type: string
          format: date-time
        Status:
          type: string
      required:
        - CreatedBy
        - Percent
        - StartedAt
        - EndedAt
        - Status
    TaskUpdate:
      type: object
      properties:
        UUID:
          type: string
          format: uuid
        CreatedBy:
          type: string
          format: uuid
        Percent:
          type: number
        StartedAt:
          type: string
          format: date-time
        EndedAt:
          type: string
          format: date-time
        Status:
          type: string
      required:
        - UUID
        - CreatedBy
        - Percent
        - StartedAt
        - EndedAt
        - Status
    TaskFilter:
      type: object
      properties:
        UUID:
          type: string
          format: uuid
        CreatedBy:
          type: string
          format: uuid
        Percent:
          type: number
        Status:
          type: string
    ModelUUID:
      type: object
      properties:
        UUID:
          type: string
          format: uuid
      required:
        - UUID
